//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FineLocalizer.Lang {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MsgBoxFineLo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MsgBoxFineLo() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FineLocalizer.Lang.MsgBoxFineLo", typeof(MsgBoxFineLo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   You could not remove the last camera setting.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CantRemoveLastCam {
            get {
                return ResourceManager.GetString("CantRemoveLastCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You cound not remove the last car settings.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CantRemoveLastCar {
            get {
                return ResourceManager.GetString("CantRemoveLastCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong pasword..과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeModePasswordFailed {
            get {
                return ResourceManager.GetString("ChangeModePasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid car type! It must be integer.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidCarType {
            get {
                return ResourceManager.GetString("InvalidCarType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid license...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidLicense {
            get {
                return ResourceManager.GetString("InvalidLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid path..과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trial license expired…과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LicenseExpired {
            get {
                return ResourceManager.GetString("LicenseExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error with loading the config file..과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoadingConfigError {
            get {
                return ResourceManager.GetString("LoadingConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to close program?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MainFormClosingCheck {
            get {
                return ResourceManager.GetString("MainFormClosingCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You should input the variable&apos;s name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NeedVarName {
            get {
                return ResourceManager.GetString("NeedVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Offset Value.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OffsetValueNotValid {
            get {
                return ResourceManager.GetString("OffsetValueNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error with scanning point.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PointScanError {
            get {
                return ResourceManager.GetString("PointScanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program is Already Running과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProgramAlreadyRunning {
            get {
                return ResourceManager.GetString("ProgramAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting Manager과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SettingManagerTitle {
            get {
                return ResourceManager.GetString("SettingManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This name already has being used.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UsedVarName {
            get {
                return ResourceManager.GetString("UsedVarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to add a robot pose variable?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WantAddRobotPoseVar {
            get {
                return ResourceManager.GetString("WantAddRobotPoseVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to modify the RobotPose variable name?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WantModifyRobotPosevar {
            get {
                return ResourceManager.GetString("WantModifyRobotPosevar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to remove?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WantRemove {
            get {
                return ResourceManager.GetString("WantRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It will be removed from the last. Do you want to remove?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WantRemoveCamItem {
            get {
                return ResourceManager.GetString("WantRemoveCamItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to reset all settings to their default?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WantResetFactorySetting {
            get {
                return ResourceManager.GetString("WantResetFactorySetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want the current settings to be saved as the factory defaults?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WantSaveFactoryDefault {
            get {
                return ResourceManager.GetString("WantSaveFactoryDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save the image?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WantSaveRefImg {
            get {
                return ResourceManager.GetString("WantSaveRefImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save the robot&apos;s current pose?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WantSaveRefPose {
            get {
                return ResourceManager.GetString("WantSaveRefPose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save your changes?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WantSaveSettings {
            get {
                return ResourceManager.GetString("WantSaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
    }
}
