name: python cs tokenizer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          cs2xlsx:
            - 'PythonCSharpener/FineLocalizer/**.cs'
          xl2resx:
            - 'PythonCSharpener/localization_tool/**.xlsx'

    - name: docker
      if: steps.filter.outputs.cs2xlsx == 'true' || steps.filter.outputs.xl2resx == 'true'
      run: |
        cd ./PythonCSharpener/localization_tool
        mkdir out
        docker-compose up -d
   
    - name:  make tokens and add to excel and make the resources of FineLocalizer
      if: hashFiles('./PythonCSharpener/localization_tool/CoPick.Logging.xlsx') != '' && steps.filter.outputs.cs2xlsx == 'true'
      run: |
        docker exec xl2resx_container python3 ./localization_tool/cs2xl2resx.py ./FineLocalizer ./localization_tool/CoPick.Logging.xlsx
        sudo mv ./PythonCSharpener/localization_tool/out/*.resx ./PythonCSharpener/FineLocalizer/Lang/

    - name: make the resources of FineLocalizer
      if: hashFiles('./PythonCSharpener/localization_tool/CoPick.Logging.xlsx') != '' && steps.filter.outputs.cs2xlsx == 'false' && steps.filter.outputs.xl2resx == 'true'
      run: |
        docker exec xl2resx_container python3 ./localization_tool/cs2xl2resx.py ./localization_tool/CoPick.Logging.xlsx
        sudo mv ./PythonCSharpener/localization_tool/out/*.resx ./PythonCSharpener/FineLocalizer/Lang/

    - name: commit
      run: |
        sudo rm -r ./PythonCSharpener/localization_tool/out
        git config --local user.email "dev@cogaplex.com"
        git config --local user.name "CoPickDev[bot]"
        git add .
        git status
        git commit -m "Updates localization changes"

    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
